/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as PendapatanRouteImport } from './routes/pendapatan'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PppoeAktifRouteImport } from './routes/pppoe-aktif'
import { Route as RadiusRouteImport } from './routes/radius'
import { Route as SesiAktifRouteImport } from './routes/sesi-aktif'
import { Route as TagihanRouteImport } from './routes/tagihan'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as Tr069RouteImport } from './routes/tr069'
import { Route as UserAktifRouteImport } from './routes/user-aktif'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as ApiPublicLogoDotpngRouteImport } from './routes/api/public/logo[.]png'
import { Route as ApiPublicQrisDotpngRouteImport } from './routes/api/public/qris[.]png'
import { Route as ApiPublicPayCallbackProviderRouteImport } from './routes/api/public/pay-callback.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const PendapatanRoute = PendapatanRouteImport.update({
  id: '/pendapatan',
  path: '/pendapatan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PppoeAktifRoute = PppoeAktifRouteImport.update({
  id: '/pppoe-aktif',
  path: '/pppoe-aktif',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiusRoute = RadiusRouteImport.update({
  id: '/radius',
  path: '/radius',
  getParentRoute: () => rootRouteImport,
} as any)
const SesiAktifRoute = SesiAktifRouteImport.update({
  id: '/sesi-aktif',
  path: '/sesi-aktif',
  getParentRoute: () => rootRouteImport,
} as any)
const TagihanRoute = TagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const Tr069Route = Tr069RouteImport.update({
  id: '/tr069',
  path: '/tr069',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAktifRoute = UserAktifRouteImport.update({
  id: '/user-aktif',
  path: '/user-aktif',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogoDotpngRoute = ApiPublicLogoDotpngRouteImport.update({
  id: '/api/public/logo.png',
  path: '/api/public/logo.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQrisDotpngRoute = ApiPublicQrisDotpngRouteImport.update({
  id: '/api/public/qris.png',
  path: '/api/public/qris.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayCallbackProviderRoute =
  ApiPublicPayCallbackProviderRouteImport.update({
    id: '/api/public/pay-callback/$provider',
    path: '/api/public/pay-callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/laporan': typeof LaporanRoute
  '/paket': typeof PaketRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengaturan': typeof PengaturanRoute
  '/portal': typeof PortalRoute
  '/pppoe-aktif': typeof PppoeAktifRoute
  '/radius': typeof RadiusRoute
  '/sesi-aktif': typeof SesiAktifRoute
  '/tagihan': typeof TagihanRoute
  '/template': typeof TemplateRoute
  '/tr069': typeof Tr069Route
  '/user-aktif': typeof UserAktifRoute
  '/voucher': typeof VoucherRoute
  '/vpn': typeof VpnRoute
  '/api/public/logo.png': typeof ApiPublicLogoDotpngRoute
  '/api/public/qris.png': typeof ApiPublicQrisDotpngRoute
  '/api/public/pay-callback/$provider': typeof ApiPublicPayCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/laporan': typeof LaporanRoute
  '/paket': typeof PaketRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengaturan': typeof PengaturanRoute
  '/portal': typeof PortalRoute
  '/pppoe-aktif': typeof PppoeAktifRoute
  '/radius': typeof RadiusRoute
  '/sesi-aktif': typeof SesiAktifRoute
  '/tagihan': typeof TagihanRoute
  '/template': typeof TemplateRoute
  '/tr069': typeof Tr069Route
  '/user-aktif': typeof UserAktifRoute
  '/voucher': typeof VoucherRoute
  '/vpn': typeof VpnRoute
  '/api/public/logo.png': typeof ApiPublicLogoDotpngRoute
  '/api/public/qris.png': typeof ApiPublicQrisDotpngRoute
  '/api/public/pay-callback/$provider': typeof ApiPublicPayCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/laporan': typeof LaporanRoute
  '/paket': typeof PaketRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengaturan': typeof PengaturanRoute
  '/portal': typeof PortalRoute
  '/pppoe-aktif': typeof PppoeAktifRoute
  '/radius': typeof RadiusRoute
  '/sesi-aktif': typeof SesiAktifRoute
  '/tagihan': typeof TagihanRoute
  '/template': typeof TemplateRoute
  '/tr069': typeof Tr069Route
  '/user-aktif': typeof UserAktifRoute
  '/voucher': typeof VoucherRoute
  '/vpn': typeof VpnRoute
  '/api/public/logo.png': typeof ApiPublicLogoDotpngRoute
  '/api/public/qris.png': typeof ApiPublicQrisDotpngRoute
  '/api/public/pay-callback/$provider': typeof ApiPublicPayCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivasi'
    | '/laporan'
    | '/paket'
    | '/pendapatan'
    | '/pengaturan'
    | '/portal'
    | '/pppoe-aktif'
    | '/radius'
    | '/sesi-aktif'
    | '/tagihan'
    | '/template'
    | '/tr069'
    | '/user-aktif'
    | '/voucher'
    | '/vpn'
    | '/api/public/logo.png'
    | '/api/public/qris.png'
    | '/api/public/pay-callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivasi'
    | '/laporan'
    | '/paket'
    | '/pendapatan'
    | '/pengaturan'
    | '/portal'
    | '/pppoe-aktif'
    | '/radius'
    | '/sesi-aktif'
    | '/tagihan'
    | '/template'
    | '/tr069'
    | '/user-aktif'
    | '/voucher'
    | '/vpn'
    | '/api/public/logo.png'
    | '/api/public/qris.png'
    | '/api/public/pay-callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/aktivasi'
    | '/laporan'
    | '/paket'
    | '/pendapatan'
    | '/pengaturan'
    | '/portal'
    | '/pppoe-aktif'
    | '/radius'
    | '/sesi-aktif'
    | '/tagihan'
    | '/template'
    | '/tr069'
    | '/user-aktif'
    | '/voucher'
    | '/vpn'
    | '/api/public/logo.png'
    | '/api/public/qris.png'
    | '/api/public/pay-callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivasiRoute: typeof AktivasiRoute
  LaporanRoute: typeof LaporanRoute
  PaketRoute: typeof PaketRoute
  PendapatanRoute: typeof PendapatanRoute
  PengaturanRoute: typeof PengaturanRoute
  PortalRoute: typeof PortalRoute
  PppoeAktifRoute: typeof PppoeAktifRoute
  RadiusRoute: typeof RadiusRoute
  SesiAktifRoute: typeof SesiAktifRoute
  TagihanRoute: typeof TagihanRoute
  TemplateRoute: typeof TemplateRoute
  Tr069Route: typeof Tr069Route
  UserAktifRoute: typeof UserAktifRoute
  VoucherRoute: typeof VoucherRoute
  VpnRoute: typeof VpnRoute
  ApiPublicLogoDotpngRoute: typeof ApiPublicLogoDotpngRoute
  ApiPublicQrisDotpngRoute: typeof ApiPublicQrisDotpngRoute
  ApiPublicPayCallbackProviderRoute: typeof ApiPublicPayCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendapatan': {
      id: '/pendapatan'
      path: '/pendapatan'
      fullPath: '/pendapatan'
      preLoaderRoute: typeof PendapatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppoe-aktif': {
      id: '/pppoe-aktif'
      path: '/pppoe-aktif'
      fullPath: '/pppoe-aktif'
      preLoaderRoute: typeof PppoeAktifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radius': {
      id: '/radius'
      path: '/radius'
      fullPath: '/radius'
      preLoaderRoute: typeof RadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesi-aktif': {
      id: '/sesi-aktif'
      path: '/sesi-aktif'
      fullPath: '/sesi-aktif'
      preLoaderRoute: typeof SesiAktifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagihan': {
      id: '/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof TagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr069': {
      id: '/tr069'
      path: '/tr069'
      fullPath: '/tr069'
      preLoaderRoute: typeof Tr069RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-aktif': {
      id: '/user-aktif'
      path: '/user-aktif'
      fullPath: '/user-aktif'
      preLoaderRoute: typeof UserAktifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logo.png': {
      id: '/api/public/logo.png'
      path: '/api/public/logo.png'
      fullPath: '/api/public/logo.png'
      preLoaderRoute: typeof ApiPublicLogoDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qris.png': {
      id: '/api/public/qris.png'
      path: '/api/public/qris.png'
      fullPath: '/api/public/qris.png'
      preLoaderRoute: typeof ApiPublicQrisDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay-callback/$provider': {
      id: '/api/public/pay-callback/$provider'
      path: '/api/public/pay-callback/$provider'
      fullPath: '/api/public/pay-callback/$provider'
      preLoaderRoute: typeof ApiPublicPayCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivasiRoute: AktivasiRoute,
  LaporanRoute: LaporanRoute,
  PaketRoute: PaketRoute,
  PendapatanRoute: PendapatanRoute,
  PengaturanRoute: PengaturanRoute,
  PortalRoute: PortalRoute,
  PppoeAktifRoute: PppoeAktifRoute,
  RadiusRoute: RadiusRoute,
  SesiAktifRoute: SesiAktifRoute,
  TagihanRoute: TagihanRoute,
  TemplateRoute: TemplateRoute,
  Tr069Route: Tr069Route,
  UserAktifRoute: UserAktifRoute,
  VoucherRoute: VoucherRoute,
  VpnRoute: VpnRoute,
  ApiPublicLogoDotpngRoute: ApiPublicLogoDotpngRoute,
  ApiPublicQrisDotpngRoute: ApiPublicQrisDotpngRoute,
  ApiPublicPayCallbackProviderRoute: ApiPublicPayCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
